Repository sdpython/mlprodict, pull requests merged in 2021-12, with the labels that each got.

#325 Implements a simple text display for ONNX graph
  .circleci/config.yml
  _doc/sphinxdoc/source/api/tools.rst
  _unittests/ut_plotting/test_text_plotting.py
  mlprodict/plotting/plotting.py
  mlprodict/plotting/text_plot.py
Labels: enhancement

#326 Better error messages when name is shared with results and node name in onnx_simple_text_plot
  mlprodict/plotting/text_plot.py
Labels: bug

#327 Adds runtime for operator LeakyRelu
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  mlprodict/onnxrt/ops_cpu/_op_list.py
  mlprodict/onnxrt/ops_cpu/op_leaky_relu.py
  mlprodict/onnxrt/validate/validate_python.py
Labels: operator

#328 Extends command line onnx_stats
  _unittests/ut_cli/test_cli_onnx_stats.py
  _unittests/ut_plotting/test_text_plotting.py
  _unittests/ut_tools/test_optim_onnx_identity.py
  mlprodict/cli/optimize.py
  mlprodict/onnx_tools/optim/onnx_helper.py
  mlprodict/plotting/plotting.py
  mlprodict/plotting/text_plot.py
Labels: enhancement

#329 Fixes type issue in shape inference for operator If
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_control_if.py
  _unittests/ut_onnxrt/test_onnxrt_simple.py
  _unittests/ut_plotting/test_text_plotting.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/onnx_inference_exports.py
  mlprodict/onnxrt/ops_cpu/op_if.py
  mlprodict/plotting/text_plot.py
Labels: bug

#330 Reduces verbosity when onnxruntime is used as a runtime for OnnxInference
  _unittests/ut_tools/test_export_onnx.py
  mlprodict/asv_benchmark/common_asv_skl.py
  mlprodict/cli/convert_validate.py
  mlprodict/onnxrt/onnx_inference_node.py
  mlprodict/onnxrt/ops_whole/session.py
  mlprodict/onnxrt/validate/validate.py
  mlprodict/onnxrt/validate/validate_benchmark_replay.py
  mlprodict/sklapi/onnx_transformer.py
  mlprodict/testing/einsum/einsum_fct.py
  mlprodict/testing/test_utils/quantized_tensor.py
  mlprodict/tools/zoo.py
Labels: enhancement

#331 Removes measure_time
  _doc/examples/plot_onnx_tree_ensemble_parallel.py
  _doc/examples/plot_op_add.py
  _doc/examples/plot_op_einsum.py
  _doc/examples/plot_op_onnx_topk.py
  _doc/examples/plot_op_reducemax.py
  _doc/examples/plot_op_reducemean.py
  _doc/examples/plot_op_reducesum.py
  _doc/examples/plot_op_reducesumsquare.py
  _doc/examples/plot_op_transpose.py
  _doc/examples/plot_op_where.py
  _doc/examples/plot_parallelism.py
  _doc/examples/plot_speedup_pca.py
  _doc/notebooks/topk_cpp.ipynb
  _doc/sphinxdoc/source/api/tools.rst
  _doc/sphinxdoc/source/index.rst
  _unittests/ut_onnxrt/test_onnxrt_simple.py
  _unittests/ut_tools/test_mesure_time.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/onnx_inference_exports.py
  mlprodict/onnxrt/validate/validate_benchmark.py
  mlprodict/onnxrt/validate/validate_helper.py
  mlprodict/testing/bench_helper.py
  mlprodict/testing/einsum/einsum_bench.py
  mlprodict/tools/__init__.py
  mlprodict/tools/speed_measure.py
  requirements.txt
Labels: refactoring

#332 Improves dot rendering, fixes disconnected subgraphs
  README.rst
  _unittests/ut_onnxrt/test_onnxrt_simple.py
  mlprodict/onnxrt/onnx_inference_exports.py
Labels: bug

#333 Adds command line latency to measure the latency of a runtime
  _doc/sphinxdoc/source/tutorial/benchmark.rst
  _unittests/ut_cli/test_cli_latency.py
  mlprodict/__main__.py
  mlprodict/cli/__init__.py
  mlprodict/cli/latency_cli.py
  mlprodict/cli/optimize.py
  mlprodict/cli/replay.py
  mlprodict/cli/validate.py
  mlprodict/onnx_tools/optim/_onnx_optimisation_common.py
Labels: enhancement

#336 Enables GPU with OnnxInference and onnxruntime
  _doc/sphinxdoc/source/api/onnxrt.rst
  _unittests/ut_onnxrt/test_onnxrt_iobinding.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/ops_whole/session.py
  mlprodict/tools/onnx_inference_ort_helper.py
  mlprodict/tools/ort_wrapper.py
Labels: enhancement

#337 Supports operator Scan when exporting an onnx graph to onnx code
  _unittests/ut_tools/data/SklearnKNeighborsRegressor2.model.onnx
  _unittests/ut_tools/test_export_onnx.py
  mlprodict/onnx_tools/_onnx_export_templates_onnx.tmpl
  mlprodict/onnx_tools/onnx_export.py
Labels: enhancement

#339 op_label_encoder support for keys_strings & values_floats (2) (replaces #335)
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_ml_text.py
  mlprodict/onnxrt/ops_cpu/op_label_encoder.py
Labels: enhancement, converter
