Repository sdpython/mlprodict, pull requests merged in 2021-07, with the labels that each got.

#280 More robustness for the python runtime
  _doc/examples/plot_op_where.py
  _unittests/ut__skl2onnx/test_sklearn_pipeline.py
  _unittests/ut_npy/test_onnx_variable.py
  _unittests/ut_npy/test_onnx_variable_ort.py
  _unittests/ut_npy/test_onnx_variable_tuple.py
  _unittests/ut_npy/test_wrappers.py
  _unittests/ut_onnx_conv/test_onnx_conv_dataframe.py
  _unittests/ut_onnx_conv/test_onnxrt_runtime_xgboost.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_ml.py
  _unittests/ut_onnxrt/test_onnxrt_validate_bug.py
  _unittests/ut_onnxrt/test_onnxrt_validate_type.py
  mlprodict/asv_benchmark/_create_asv_helper.py
  mlprodict/cli/convert_validate.py
  mlprodict/grammar_sklearn/grammar/gtypes.py
  mlprodict/npy/onnx_numpy_annotation.py
  mlprodict/npy/onnx_variable.py
  mlprodict/onnx_conv/convert.py
  mlprodict/onnx_tools/onnx2py_helper.py
  mlprodict/onnx_tools/optim/onnx_optimisation.py
  mlprodict/onnx_tools/optim/onnx_optimisation_identity.py
  mlprodict/onnx_tools/optim/onnx_optimisation_redundant.py
  mlprodict/onnx_tools/optim/onnx_optimisation_unused.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/ops_cpu/_op.py
  mlprodict/onnxrt/ops_cpu/_op_classifier_string.py
  mlprodict/onnxrt/ops_cpu/_op_helper.py
  mlprodict/onnxrt/ops_cpu/op_cast.py
  mlprodict/onnxrt/ops_cpu/op_cdist.py
  mlprodict/onnxrt/ops_cpu/op_constant.py
  mlprodict/onnxrt/ops_cpu/op_constant_of_shape.py
  mlprodict/onnxrt/ops_cpu/op_dict_vectorizer.py
  mlprodict/onnxrt/ops_cpu/op_label_encoder.py
  mlprodict/onnxrt/ops_cpu/op_one_hot_encoder.py
  mlprodict/onnxrt/ops_cpu/op_solve.py
  mlprodict/onnxrt/ops_cpu/op_zipmap.py
  mlprodict/onnxrt/shape_object.py
  mlprodict/sklapi/onnx_transformer.py
  mlprodict/testing/einsum/einsum_impl_classes.py
  mlprodict/testing/test_utils/quantized_tensor.py
  mlprodict/testing/test_utils/utils_backend_common.py
  mlprodict/tools/filename_helper.py
Labels: enhancement

#282 Upgrade requirements to skl2onnx>=1.9.0
  requirements.txt
  setup.py
Labels: Opset 14

#284 Adds function transpose to numpy API for ONNX
  _doc/notebooks/onnx_fft.ipynb
  _unittests/ut_documentation/test_run_notebooks_fft.py
  _unittests/ut_npy/test_numpy_onnx_pyrt.py
  _unittests/ut_npy/test_onnx_variable.py
  _unittests/ut_npy/test_onnx_variable_ort.py
  _unittests/ut_onnxrt/test_onnxrt_validate_bug.py
  mlprodict/npy/numpy_onnx_impl.py
  mlprodict/npy/numpy_onnx_pyrt.py
  mlprodict/npy/onnx_numpy_compiler.py
  mlprodict/npy/onnx_variable.py
  mlprodict/onnxrt/ops_cpu/_op_numpy_helper.py
  mlprodict/onnxrt/shape_object.py
  requirements.txt
Labels: API, enhancement

#285 Adds function cst to create constant with numpy API for ONNX
  _doc/sphinxdoc/source/tutorial/numpy_api_onnx.rst
  _unittests/ut_npy/test_onnx_variable.py
  mlprodict/npy/numpy_onnx_impl.py
  mlprodict/npy/onnx_variable.py
Labels: API

#286 Adds runtime for operator Range
  .circleci/config.yml
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  mlprodict/onnxrt/ops_cpu/_op_list.py
  mlprodict/onnxrt/ops_cpu/op_range.py
Labels: runtime

#288 Extends code coverage
  _unittests/ut__skl2onnx/test_sklearn_gaussian_process.py
  _unittests/ut_cli/test_cli_benchmark_replay.py
  _unittests/ut_cli/test_cli_validate_dump.py
  _unittests/ut_cli/test_cli_validate_runtime.py
  _unittests/ut_documentation/test_run_notebooks_onnx_profile.py
  _unittests/ut_module/test_code_style.py
  _unittests/ut_npy/test_onnx_variable.py
  _unittests/ut_onnx_conv/test_onnxrt_runtime_lightgbm.py
  _unittests/ut_onnx_conv/test_onnxrt_runtime_randomforest_decision_path.py
  _unittests/ut_onnx_conv/test_onnxrt_runtime_xgboost.py
  _unittests/ut_onnx_conv/test_rt_valid_lightgbm.py
  _unittests/ut_onnx_conv/test_rt_valid_model_lightgbm.py
  _unittests/ut_onnx_conv/test_rt_valid_xgboost.py
  _unittests/ut_onnxrt/test_benchmark_replay.py
  _unittests/ut_onnxrt/test_onnx_inference.py
  _unittests/ut_onnxrt/test_onnxrt_model_shaker.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  _unittests/ut_onnxrt/test_onnxrt_validate_2.py
  _unittests/ut_onnxrt/test_onnxrt_validate_benchmark.py
  _unittests/ut_onnxrt/test_onnxrt_validate_bug.py
  _unittests/ut_onnxrt/test_onnxrt_validate_node_time.py
  _unittests/ut_onnxrt/test_onnxrt_validate_type.py
  _unittests/ut_testing/test_einsum_einsum.py
  _unittests/ut_testing/test_einsum_generic_dot.py
  _unittests/ut_testing/test_einsum_ml.py
  _unittests/ut_testing/test_verify_code.py
  _unittests/ut_tools/test_model_info.py
  azure-pipelines.yml
  mlprodict/npy/onnx_sklearn_wrapper.py
  mlprodict/npy/onnx_variable.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/onnx_inference_node.py
  mlprodict/testing/einsum/einsum_bench.py
Labels: coverage

#287 Adds python runtime for operator Loop, SequenceInsert, ConcatFromSequence
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_control_loop.py
  mlprodict/onnxrt/ops_cpu/_op.py
  mlprodict/onnxrt/ops_cpu/_op_list.py
  mlprodict/onnxrt/ops_cpu/op_concat_from_sequence.py
  mlprodict/onnxrt/ops_cpu/op_loop.py
  mlprodict/onnxrt/ops_cpu/op_sequence_insert.py
  mlprodict/onnxrt/ops_cpu/op_unsqueeze.py
  mlprodict/onnxrt/shape_object.py
Labels: runtime

#289 Avoids raising an exception when an optional parameter is not specified
  mlprodict/onnxrt/ops_cpu/_op.py
Labels: bug

#290 Increases code coverage, add infer_size for Loop runtime
  _doc/examples/plot_time_tree_ensemble.py
  _unittests/ut_cli/test_cli_asv2csv.py
  _unittests/ut_cli/test_cli_validate.py
  _unittests/ut_grammar_sklearn/test_grammar_sklearn_cov.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_control_loop.py
  _unittests/ut_tools/test_onnx_micro_runtime.py
  mlprodict/grammar_sklearn/grammar/api_extension.py
  mlprodict/onnx_tools/optim/graph_schema_helper.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/ops_cpu/_op.py
  mlprodict/onnxrt/ops_cpu/_op_list.py
  mlprodict/onnxrt/ops_cpu/op_constant.py
  mlprodict/onnxrt/ops_cpu/op_label_encoder.py
  mlprodict/onnxrt/ops_cpu/op_loop.py
  mlprodict/onnxrt/ops_cpu/op_where.py
  mlprodict/onnxrt/type_object.py
  mlprodict/tools/ort_wrapper.py
Labels: coverage

#292 Adds operator AveragePool to the python runtime
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  mlprodict/onnxrt/ops_cpu/_op_list.py
  mlprodict/onnxrt/ops_cpu/op_average_pool.py
Labels: runtime

#294 Implements text representation of an ONNX graph (bigraph)
  _unittests/ut_onnxrt/test_onnxrt_simple.py
  _unittests/ut_tools/test_graphs.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/onnx_inference_exports.py
  mlprodict/tools/graphs.py
Labels: enhancement

#291 Fixes infinite loop with operator loop, add support for static variables in Loop
  _unittests/ut_onnxrt/test_onnx_inference.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_control_loop.py
  _unittests/ut_tools/data/bug_graph.onnx
  _unittests/ut_tools/data/bug_graph_infinite.onnx
  _unittests/ut_tools/test_code_helper.py
  _unittests/ut_tools/test_graphs.py
  mlprodict/__init__.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/onnx_inference_exports.py
  mlprodict/onnxrt/onnx_inference_node.py
  mlprodict/onnxrt/ops_cpu/_op.py
  mlprodict/onnxrt/ops_cpu/op_concat_from_sequence.py
  mlprodict/onnxrt/ops_cpu/op_conv.py
  mlprodict/onnxrt/ops_cpu/op_gather.py
  mlprodict/onnxrt/ops_cpu/op_loop.py
  mlprodict/onnxrt/ops_cpu/op_reshape.py
  mlprodict/onnxrt/ops_cpu/op_sequence_insert.py
  mlprodict/onnxrt/ops_empty/_op.py
  mlprodict/onnxrt/ops_onnxruntime/_op.py
  mlprodict/onnxrt/shape_object.py
  mlprodict/tools/code_helper.py
  mlprodict/tools/graphs.py
  requirements.txt
Labels: bug
