Repository sdpython/mlprodict, pull requests merged in 2021-08, with the labels that each got.

#295 Implements runtime for operator FFT
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_custom.py
  mlprodict/onnx_conv/onnx_ops/__init__.py
  mlprodict/onnx_conv/onnx_ops/onnx_complex.py
  mlprodict/onnx_conv/onnx_ops/onnx_fft.py
  mlprodict/onnx_tools/onnx2py_helper.py
  mlprodict/onnxrt/ops_cpu/_op.py
  mlprodict/onnxrt/ops_cpu/_op_list.py
  mlprodict/onnxrt/ops_cpu/op_complex_abs.py
  mlprodict/onnxrt/ops_cpu/op_fft.py
  mlprodict/onnxrt/ops_cpu/op_fft2d.py
  mlprodict/onnxrt/ops_cpu/op_rfft.py
  mlprodict/onnxrt/ops_cpu/op_solve.py
  mlprodict/onnxrt/shape_object.py
  mlprodict/onnxrt/validate/validate_python.py
Labels: operator

#296 Lightgbm + add function matmul to numpy API for ONNX
  _doc/notebooks/onnx_fft.ipynb
  _doc/sphinxdoc/source/api/tools.rst
  _doc/sphinxdoc/source/blog/2021/2021-05-05_numpyapionnx1.rst
  _unittests/ut_cli/test_cli_onnx_code.py
  _unittests/ut_npy/test_onnx_variable.py
  _unittests/ut_onnx_conv/test_onnxrt_runtime_lightgbm.py
  _unittests/ut_onnx_conv/test_onnxrt_runtime_lightgbm_bug.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_custom.py
  _unittests/ut_tools/data/fft2d_any.onnx
  _unittests/ut_tools/test_export_onnx.py
  mlprodict/__main__.py
  mlprodict/cli/__init__.py
  mlprodict/cli/onnx_code.py
  mlprodict/npy/numpy_onnx_impl.py
  mlprodict/npy/numpy_onnx_pyrt.py
  mlprodict/onnx_tools/exports/__init__.py
  mlprodict/onnx_tools/exports/tf2onnx_helper.py
  mlprodict/onnx_tools/onnx2py_helper.py
  mlprodict/onnx_tools/onnx_export.py
  mlprodict/onnx_tools/onnx_tools.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/ops_cpu/_op_helper.py
  mlprodict/testing/verify_code.py
Labels: ci

#297 Adds function to convert ONNX into numpy code.
  .circleci/config.yml
  _doc/notebooks/onnx_fft.ipynb
  _doc/notebooks/onnx_float32_and_64.ipynb
  _doc/notebooks/onnx_sbs.ipynb
  _doc/sphinxdoc/source/api/tools.rst
  _doc/sphinxdoc/source/blog/2021/2021-08-10_shape.rst
  _doc/sphinxdoc/source/blog/2021/2021-08-11_einsum.rst
  _doc/sphinxdoc/source/blog/2021/2021-08-12_tf2onnx.rst
  _unittests/ut_cli/test_cli_onnx_code.py
  _unittests/ut_npy/test_numpy_onnx_pyrt.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_custom.py
  _unittests/ut_onnxrt/test_onnxrt_side_by_side.py
  _unittests/ut_onnxrt/test_rt_valid_model_adaboost.py
  _unittests/ut_tools/data/fft2d.onnx
  _unittests/ut_tools/test_export_onnx.py
  _unittests/ut_tools/test_graphs_distance.py
  _unittests/ut_tools/test_onnx_manipulations.py
  _unittests/ut_tools/test_zoo.py
  mlprodict/cli/onnx_code.py
  mlprodict/npy/numpy_onnx_impl.py
  mlprodict/npy/onnx_numpy_annotation.py
  mlprodict/npy/onnx_variable.py
  mlprodict/onnx_tools/exports/numpy_helper.py
  mlprodict/onnx_tools/exports/tf2onnx_helper.py
  mlprodict/onnx_tools/onnx2py_helper.py
  mlprodict/onnx_tools/onnx_export.py
  mlprodict/onnx_tools/onnx_manipulations.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/onnx_inference_node.py
  mlprodict/onnxrt/ops_cpu/op_concat.py
  mlprodict/onnxrt/ops_cpu/op_constant_of_shape.py
  mlprodict/onnxrt/ops_cpu/op_slice.py
  mlprodict/onnxrt/validate/side_by_side.py
  mlprodict/onnxrt/validate/validate_difference.py
  mlprodict/testing/einsum/__init__.py
  mlprodict/testing/einsum/einsum_fct.py
  mlprodict/testing/einsum/einsum_impl.py
  mlprodict/testing/einsum/einsum_impl_classes.py
  mlprodict/tools/graphs.py
  mlprodict/tools/onnx_micro_runtime.py
  requirements.txt
  setup.py
Labels: enhancement

#300 Improves Lightgbm converter design + fix wrong prediction for TreeEnsemble with non contiguous arrays
  _doc/notebooks/onnx_fft.ipynb
  _doc/sphinxdoc/source/api/sklearn.rst
  _unittests/ut_onnx_conv/test_lightgbm_tree_structure.py
  _unittests/ut_onnx_conv/test_onnxrt_runtime_lightgbm.py
  _unittests/ut_onnx_conv/test_onnxrt_runtime_lightgbm_bug.py
  _unittests/ut_tools/test_graphs.py
  mlprodict/onnx_conv/convert.py
  mlprodict/onnx_conv/helpers/__init__.py
  mlprodict/onnx_conv/helpers/lgbm_helper.py
  mlprodict/onnx_conv/operator_converters/conv_lightgbm.py
  mlprodict/onnx_conv/parsers/parse_lightgbm.py
  mlprodict/onnx_tools/onnx_export.py
  mlprodict/onnx_tools/onnx_export_templates.py
  mlprodict/onnxrt/ops_cpu/op_conv_.cpp
  mlprodict/onnxrt/ops_cpu/op_conv_transpose_.cpp
  mlprodict/onnxrt/ops_cpu/op_max_pool_.cpp
  mlprodict/onnxrt/ops_cpu/op_svm_classifier_.cpp
  mlprodict/onnxrt/ops_cpu/op_svm_common_.hpp
  mlprodict/onnxrt/ops_cpu/op_svm_regressor_.cpp
  mlprodict/onnxrt/ops_cpu/op_tfidfvectorizer_.cpp
  mlprodict/onnxrt/ops_cpu/op_tree_ensemble_classifier_.cpp
  mlprodict/onnxrt/ops_cpu/op_tree_ensemble_classifier_p_.cpp
  mlprodict/onnxrt/ops_cpu/op_tree_ensemble_common_p_.hpp
  mlprodict/onnxrt/ops_cpu/op_tree_ensemble_regressor_.cpp
  mlprodict/onnxrt/ops_cpu/op_tree_ensemble_regressor_p_.cpp
  mlprodict/tools/graphs.py
  requirements.txt
  setup.py
Labels: enhancement

#301 Different build for manylinux on python 3.9
  azure-pipelines.yml
Labels: ci

#302 Removes unused nodes after changing the outputs.
  .circleci/config.yml
  _unittests/ut_tools/test_onnx_manipulations.py
  _unittests/ut_tools/test_optim_onnx_identity.py
  _unittests/ut_tools/test_optim_onnx_redundant.py
  _unittests/ut_tools/test_optim_onnx_unused.py
  mlprodict/onnx_tools/onnx_manipulations.py
  mlprodict/onnx_tools/optim/onnx_optimisation.py
Labels: performance

#303 Implements a estimator speeding up the inference using ONNX
  .gitignore
  _doc/examples/plot_speedup_pca.py
  _doc/examples/plot_time_tree_ensemble.py
  _doc/sphinxdoc/source/_exts/generate_automated_pages.py
  _doc/sphinxdoc/source/api/sklapi.rst
  _doc/sphinxdoc/source/api/tools.rst
  _doc/sphinxdoc/source/conf.py
  _unittests/ut_onnxrt/test_onnx_inference_to_python.py
  _unittests/ut_onnxrt/test_rt_valid_model_grid_search_cv.py
  _unittests/ut_sklapi/test_onnx_speedup_classifier.py
  _unittests/ut_sklapi/test_onnx_speedup_cluster.py
  _unittests/ut_sklapi/test_onnx_speedup_regressor.py
  _unittests/ut_sklapi/test_onnx_speedup_transformer.py
  _unittests/ut_tools/data/debug.onnx
  _unittests/ut_tools/test_export_onnx.py
  _unittests/ut_tools/test_onnx2py_helper.py
  mlprodict/onnx_conv/convert.py
  mlprodict/onnx_tools/_onnx_export_templates_numpy.tmpl
  mlprodict/onnx_tools/exports/numpy_helper.py
  mlprodict/onnx_tools/exports/skl2onnx_helper.py
  mlprodict/onnx_tools/exports/tf2onnx_helper.py
  mlprodict/onnx_tools/onnx2py_helper.py
  mlprodict/onnx_tools/onnx_export.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/onnx_inference_exports.py
  mlprodict/sklapi/__init__.py
  mlprodict/sklapi/onnx_speed_up.py
  mlprodict/sklapi/onnx_transformer.py
Labels: performance
