Repository sdpython/mlprodict, pull requests merged in 2021-11, with the labels that each got.

#318 Disable onnxruntime optimisation on one particular graph
  _unittests/ut_tools/test_export_onnx.py
  mlprodict/onnxrt/ops_whole/session.py
Labels: ci

#320 Fix exporter to tf2onnx
  _unittests/ut_onnx_conv/test_onnxrt_runtime_lightgbm.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  _unittests/ut_sklapi/test_onnx_speedup_regressor.py
  _unittests/ut_tools/data/gslice.onnx
  _unittests/ut_tools/data/gsqueeze.onnx
  _unittests/ut_tools/test_export_onnx.py
  mlprodict/npy/onnx_variable.py
  mlprodict/onnx_conv/helpers/lgbm_helper.py
  mlprodict/onnx_tools/_onnx_export_templates_tf2onnx.tmpl
  mlprodict/onnx_tools/exports/tf2onnx_helper.py
  mlprodict/onnx_tools/onnx2py_helper.py
  mlprodict/onnx_tools/onnx_export.py
  mlprodict/onnx_tools/onnx_manipulations.py
  mlprodict/onnx_tools/onnx_tools.py
  mlprodict/onnxrt/onnx_inference_node.py
  mlprodict/onnxrt/ops_cpu/op_constant.py
  mlprodict/onnxrt/ops_cpu/op_conv.py
  mlprodict/onnxrt/ops_cpu/op_squeeze.py
  mlprodict/onnxrt/ops_onnxruntime/_op.py
  mlprodict/sklapi/onnx_speed_up.py
  mlprodict/testing/einsum/blas_lapack.py
  mlprodict/testing/einsum/einsum_fct.py
  mlprodict/testing/einsum/einsum_impl_ext.py
  mlprodict/testing/test_utils/quantized_tensor.py
Labels: bug

#323 Implements if with numpy API
  _doc/sphinxdoc/source/conf.py
  _unittests/ut_npy/test_onnx_if.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_control_if.py
  _unittests/ut_tools/test_model_info.py
  _unittests/ut_tools/test_optim_onnx_identity.py
  mlprodict/asv_benchmark/_create_asv_helper.py
  mlprodict/npy/numpy_onnx_impl.py
  mlprodict/npy/numpy_onnx_impl_body.py
  mlprodict/npy/onnx_numpy_compiler.py
  mlprodict/npy/onnx_variable.py
Labels: API

#324 Adds runtime for gradient operators YieldOp, BroadcastGradientArgs
  _doc/sphinxdoc/source/api/tools.rst
  _unittests/ut_onnxrt/data/fw_train_LinearRegression.onnx
  _unittests/ut_onnxrt/data/fw_train_LogisticRegression.onnx
  _unittests/ut_onnxrt/test_bugs_onnxconverter.py
  _unittests/ut_onnxrt/test_onnxrt_compiled.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_custom.py
  mlprodict/onnx_conv/onnx_ops/__init__.py
  mlprodict/onnx_conv/onnx_ops/onnx_complex.py
  mlprodict/onnx_conv/onnx_ops/onnx_gradient_op.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/ops_cpu/_op.py
  mlprodict/onnxrt/ops_cpu/_op_list.py
  mlprodict/onnxrt/ops_cpu/op_broadcast_gradient_args.py
  mlprodict/onnxrt/ops_cpu/op_fused_matmul.py
  mlprodict/onnxrt/ops_cpu/op_gemm.py
  mlprodict/onnxrt/ops_cpu/op_reduce_sum.py
  mlprodict/onnxrt/ops_cpu/op_softmax.py
  mlprodict/onnxrt/ops_cpu/op_yield_op.py
  mlprodict/onnxrt/ops_onnxruntime/_op.py
  mlprodict/onnxrt/validate/validate.py
Labels: operator
