Repository sdpython/mlprodict, pull requests merged in 2021-09, with the labels that each got.

#304 Add tree text visualization for TreeEnsemble
  _doc/sphinxdoc/source/api/tools.rst
  _unittests/ut_plotting/test_text_plotting.py
  mlprodict/plotting/plotting.py
  mlprodict/plotting/plotting_onnx.py
  mlprodict/plotting/text_plot.py
Labels: enhancement

#307 Adds runtime for operator SequenceConstruct
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_ml_text.py
  mlprodict/onnxrt/ops_cpu/_op_list.py
  mlprodict/onnxrt/ops_cpu/op_sequence_construct.py
Labels: runtime, operator

#308 Adds function to rename all results in ONNX graphs
  _doc/sphinxdoc/source/api/tools.rst
  _unittests/ut_onnx_conv/test_onnx_conv_graph_optimisation.py
  _unittests/ut_tools/test_onnx_manipulations.py
  mlprodict/onnx_conv/convert.py
  mlprodict/onnx_tools/onnx_manipulations.py
  mlprodict/onnx_tools/optim/onnx_optimisation_identity.py
  mlprodict/onnx_tools/optim/onnx_optimisation_redundant.py
Labels: enhancement

#310 Raise an exception when inplace and intermediate are True (OnnxInference.run)
  _unittests/ut_onnxrt/test_onnx_inference.py
  _unittests/ut_onnxrt/test_onnxrt_onnxruntime_runtime_.py
  _unittests/ut_onnxrt/test_onnxrt_side_by_side.py
  _unittests/ut_tools/test_onnx_manipulations.py
  _unittests/ut_tools/test_zoo.py
  mlprodict/onnx_tools/onnx2py_helper.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/ops_cpu/op_string_normalizer.py
Labels: bug
