Repository sdpython/mlprodict, pull requests merged in 2021-06, with the labels that each got.

#269 Adds runtime for operator QLinearConv
  README.rst
  _doc/sphinxdoc/source/conf.py
  _doc/sphinxdoc/source/index.rst
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  bin/debug/debug.cpp
  bin/debug/debug.sln
  bin/debug/debug.vcxproj
  mlprodict/onnxrt/ops_cpu/_op_list.py
  mlprodict/onnxrt/ops_cpu/op_common_.cpp
  mlprodict/onnxrt/ops_cpu/op_common_.hpp
  mlprodict/onnxrt/ops_cpu/op_conv_.cpp
  mlprodict/onnxrt/ops_cpu/op_conv_matrices_.cpp
  mlprodict/onnxrt/ops_cpu/op_conv_matrices_.hpp
  mlprodict/onnxrt/ops_cpu/op_conv_transpose_.cpp
  mlprodict/onnxrt/ops_cpu/op_max_pool_.cpp
  mlprodict/onnxrt/ops_cpu/op_qlinear_conv.py
  mlprodict/onnxrt/ops_cpu/op_qlinear_conv_.cpp
  mlprodict/onnxrt/ops_cpu/op_qlinear_conv_.hpp
  mlprodict/onnxrt/ops_cpu/op_where.py
  setup.py
Labels: runtime

#270 Adds more tests for QLinearConv runtime
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  bin/debug/debug.cpp
  bin/debug/debug.vcxproj
  mlprodict/onnxrt/ops_cpu/_op_onnx_numpy.cpp
  mlprodict/onnxrt/ops_cpu/op_common_.cpp
  mlprodict/onnxrt/ops_cpu/op_common_.hpp
  mlprodict/onnxrt/ops_cpu/op_common_num_.cpp
  mlprodict/onnxrt/ops_cpu/op_conv_matrices_.cpp
  mlprodict/onnxrt/ops_cpu/op_conv_matrices_.hpp
  mlprodict/onnxrt/ops_cpu/op_conv_transpose_.cpp
  mlprodict/onnxrt/ops_cpu/op_max_pool_.cpp
  mlprodict/onnxrt/ops_cpu/op_qlinear_conv.py
  mlprodict/onnxrt/ops_cpu/op_qlinear_conv_.cpp
  mlprodict/onnxrt/ops_cpu/op_qlinear_conv_.hpp
  mlprodict/onnxrt/ops_cpu/op_qlinear_cpp_qgemm_tester_.cpp
  mlprodict/onnxrt/ops_cpu/op_qlinear_cpp_qgemm_tester_.hpp
  mlprodict/onnxrt/ops_cpu/op_qlinear_cpp_tester_.hpp
  mlprodict/onnxrt/ops_cpu/op_svm_classifier_.cpp
  mlprodict/onnxrt/ops_cpu/op_svm_regressor_.cpp
  mlprodict/onnxrt/ops_cpu/op_tfidfvectorizer_.cpp
  mlprodict/onnxrt/ops_cpu/op_tree_ensemble_classifier_.cpp
  mlprodict/onnxrt/ops_cpu/op_tree_ensemble_common_p_.hpp
  mlprodict/onnxrt/ops_cpu/op_tree_ensemble_regressor_.cpp
  mlprodict/onnxrt/ops_cpu/op_tree_ensemble_regressor_p_.cpp
  mlprodict/testing/experimental_c.cpp
  mlprodict/testing/test_utils/quantized_tensor.py
  setup.py
Labels: runtime

#271 Updates default opset from 13 to 14
  _doc/examples/plot_op_einsum.py
  _doc/examples/plot_op_reducemax.py
  _doc/examples/plot_op_reducemean.py
  _doc/examples/plot_op_reducesum.py
  _doc/examples/plot_op_reducesumsquare.py
  _doc/sphinxdoc/source/blog/2021/2021-05-05_numpyapionnx2.rst
  _doc/sphinxdoc/source/tutorial/numpy_api_onnx.rst
  _unittests/ut__skl2onnx/test_sklearn_label_encoder_converter.py
  _unittests/ut_asv_benchmark/test_create_asv_benchmark_pyspy.py
  _unittests/ut_onnx_conv/test_onnx_conv_knn.py
  _unittests/ut_onnxrt/test_benchmark_replay.py
  _unittests/ut_onnxrt/test_coverage_runtime_ops.py
  _unittests/ut_onnxrt/test_onnx_profiling.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  _unittests/ut_onnxrt/test_onnxrt_switch_types.py
  _unittests/ut_tools/test_ort.py
  mlprodict/testing/einsum/einsum_bench.py
  mlprodict/tools/asv_options_helper.py
Labels: Opset 14

#272 Explore custom implementation of operator add
  _unittests/ut__skl2onnx/test_sklearn_label_encoder_converter.py
  _unittests/ut_onnxrt/test_benchmark_replay.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  _unittests/ut_testing/test_custom_add.py
  bin/debug/debug.cpp
  bin/debug/debug.vcxproj
  mlprodict/onnxrt/ops_cpu/op_conv_matrices_.cpp
  mlprodict/onnxrt/ops_cpu/op_conv_matrices_.hpp
  mlprodict/onnxrt/ops_cpu/op_qlinear_conv_.cpp
  mlprodict/onnxrt/ops_cpu/op_qlinear_conv_.hpp
  mlprodict/onnxrt/ops_cpu/op_qlinear_cpp_qgemm_tester_.cpp
  mlprodict/onnxrt/ops_cpu/op_qlinear_cpp_qgemm_tester_.hpp
  mlprodict/onnxrt/ops_cpu/op_qlinear_cpp_tester_.hpp
  mlprodict/testing/experimental_c.cpp
  mlprodict/testing/experimental_c.h
  mlprodict/testing/experimental_c_add.h
  mlprodict/testing/experimental_c_add.hpp
  mlprodict/testing/experimental_c_einsum.h
  mlprodict/testing/experimental_c_einsum.hpp
  mlprodict/testing/experimental_c_helper.h
  mlprodict/testing/experimental_c_helper.hpp
  mlprodict/testing/experimental_c_reduce.h
  mlprodict/testing/experimental_c_reduce.hpp
Labels: runtime

#273 Adds operator where, improves numpy api (x[x<0]= 2)
  _doc/examples/plot_grid_search.py
  _unittests/ut_npy/test_numpy_onnx_pyrt.py
  _unittests/ut_npy/test_onnx_variable.py
  _unittests/ut_onnxrt/test_onnxrt_onnxruntime_runtime_.py
  _unittests/ut_sklapi/test_onnx_grid_search.py
  _unittests/ut_testing/data/plot_kernel_ridge_regression.py
  mlprodict/npy/numpy_onnx_impl.py
  mlprodict/npy/numpy_onnx_pyrt.py
  mlprodict/npy/onnx_variable.py
  mlprodict/onnxrt/validate/validate_scenarios.py
Labels: API, agility

#274 Fixes issue raised with scipy 1.7.0
  mlprodict/onnx_conv/scorers/cdist_score.py
Labels: bug

#275 Adds new strategy to pick up the best einsum equation based on ML
  _doc/notebooks/onnx_operator_cost.ipynb
  _doc/sphinxdoc/source/api/tools.rst
  _unittests/ut_documentation/test_run_notebooks_onnx_transpose.py
  _unittests/ut_onnxrt/test_onnxrt_onnxruntime_runtime_.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  _unittests/ut_onnxrt/test_rt_valid_model_gaussian_process_ort2.py
  _unittests/ut_testing/test_einsum.py
  _unittests/ut_testing/test_einsum_einsum.py
  _unittests/ut_testing/test_einsum_ml.py
  _unittests/ut_tools/test_onnx_manipulations.py
  _unittests/ut_tools/test_onnx_micro_runtime.py
  _unittests/ut_tools/test_ort.py
  build_script.bat
  mlprodict/onnx_tools/optim/graph_schema_helper.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/ops_cpu/op_squeeze.py
  mlprodict/onnxrt/ops_cpu/op_unsqueeze.py
  mlprodict/onnxrt/ops_onnxruntime/_op.py
  mlprodict/testing/einsum/einsum_fct.py
  mlprodict/testing/einsum/einsum_impl_classes.py
  mlprodict/testing/einsum/einsum_ml.py
  mlprodict/tools/onnx_micro_runtime.py
Labels: enhancement

#276 Use openmp to parallelize QLinearConv
  mlprodict/onnxrt/ops_cpu/op_qlinear_conv_.hpp
Labels: performance

#277 Switch to python 3.9 in CI
  .circleci/config.yml
  appveyor.yml
  azure-pipelines.yml
Labels: ci

#278 Adds operators ReduceSum, Max to OnnxMicroRuntime
  _unittests/ut_testing/test_einsum.py
  _unittests/ut_testing/test_einsum_bug.py
  _unittests/ut_testing/test_einsum_einsum.py
  mlprodict/testing/einsum/einsum_fct.py
  mlprodict/testing/einsum/einsum_impl.py
  mlprodict/testing/einsum/einsum_impl_classes.py
  mlprodict/tools/onnx_micro_runtime.py
Labels: bug, enhancement
