Repository sdpython/mlprodict, pull requests merged in 2022-08, with the labels that each got.

#458 Changes subgraph separator from :: to :/: in onnx_simple_text_plot
  _unittests/ut_plotting/data/tree_torch.onnx
  _unittests/ut_plotting/test_text_plotting.py
  mlprodict/plotting/text_plot.py
  mlprodict/testing/einsum/einsum_impl.py
  requirements.txt
Labels: bug

#461 Upgrades default supported opset to 17
  _unittests/ut__skl2onnx/test_sklearn_label_encoder_converter.py
  _unittests/ut_cli/test_cli_backend.py
  _unittests/ut_npy/test_xop_opset.py
  _unittests/ut_onnx_conv/test_onnx_conv_knn.py
  _unittests/ut_onnx_conv/test_onnx_conv_tree_ensemble.py
  _unittests/ut_onnx_conv/test_onnxrt_runtime_lightgbm.py
  _unittests/ut_onnx_conv/test_onnxrt_runtime_lightgbm_bug.py
  _unittests/ut_onnx_conv/test_onnxrt_runtime_xgboost.py
  _unittests/ut_onnxrt/test_onnx_micro_runtime.py
  _unittests/ut_onnxrt/test_onnx_profiling.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_ml_tree.py
  _unittests/ut_tools/test_export_onnx.py
  _unittests/ut_tools/test_ort.py
  _unittests/ut_tools/test_sklearn_helper.py
  mlprodict/__init__.py
  mlprodict/npy/xop.py
  mlprodict/onnx_tools/exports/numpy_helper.py
  mlprodict/onnxrt/ops_cpu/op_cum_sum.py
  requirements-osx.txt
  requirements-win.txt
  requirements.txt
  setup.py
Labels: API, Opset 17

#460 Improves C++ implementation, im2col, col2im
  _unittests/ut_onnxrt/test_cpu_ops.py
  bin/build.bat
  mlprodict/onnxrt/ops_cpu/op_common_.hpp
  mlprodict/onnxrt/ops_cpu/op_conv_.cpp
  mlprodict/onnxrt/ops_cpu/op_conv_helper.py
  mlprodict/onnxrt/ops_cpu/op_conv_helper_.cpp
  mlprodict/onnxrt/ops_cpu/op_conv_helper_.hpp
  mlprodict/onnxrt/ops_cpu/op_conv_matrices_.cpp
  mlprodict/onnxrt/ops_cpu/op_conv_matrices_.hpp
  mlprodict/onnxrt/ops_cpu/op_grid_sample_.cpp
  mlprodict/onnxrt/ops_cpu/op_roi_align_.cpp
  setup.py
Labels: code

#462 Increases code coverage, improves ligthgbm converter
  _unittests/ut_npy/test_xop_function.py
  _unittests/ut_npy/test_xop_schema.py
  _unittests/ut_onnx_conv/test_onnxrt_runtime_lightgbm.py
  _unittests/ut_onnxrt/test_coverage_any.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  _unittests/ut_plotting/data/bug_Hardmax.onnx
  _unittests/ut_plotting/test_text_plotting.py
  _unittests/ut_tools/test_bug_ort.py
  _unittests/ut_tools/test_check_model.py
  _unittests/ut_tools/test_onnx2py_helper.py
  mlprodict/cli/onnx_code.py
  mlprodict/npy/onnx_variable.py
  mlprodict/npy/xop.py
  mlprodict/onnx_conv/operator_converters/conv_lightgbm.py
  mlprodict/onnx_conv/operator_converters/parse_lightgbm.py
  mlprodict/onnx_tools/_onnx_check_model.py
  mlprodict/onnx_tools/compress.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/onnx_inference_node.py
  mlprodict/onnxrt/ops_cpu/op_expression.py
  mlprodict/onnxrt/ops_cpu/op_if.py
  mlprodict/onnxrt/ops_cpu/op_roi_align.py
  mlprodict/onnxrt/ops_cpu/op_tree_ensemble_classifier.py
  mlprodict/onnxrt/ops_cpu/op_tree_ensemble_regressor.py
  mlprodict/plotting/text_plot.py
  requirements.txt
  setup.py
Labels: coverage, code

#463 Fixes embedded if with XOP API
  _unittests/ut_npy/test_xop.py
  mlprodict/npy/xop.py
  mlprodict/plotting/text_plot.py
Labels: bug, API

#465 Supports for operator DFT, STFT, *windows
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  _unittests/ut_testing/test_onnx_backend.py
  mlprodict/npy/xop_auto.py
  mlprodict/onnx_tools/_onnx_check_model.py
  mlprodict/onnx_tools/onnx2py_helper.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/ops_cpu/_op_list.py
  mlprodict/onnxrt/ops_cpu/op_concat_from_sequence.py
  mlprodict/onnxrt/ops_cpu/op_constant.py
  mlprodict/onnxrt/ops_cpu/op_dft.py
  mlprodict/onnxrt/ops_cpu/op_layer_normalization.py
  mlprodict/onnxrt/ops_cpu/op_optional.py
  mlprodict/onnxrt/ops_cpu/op_slice.py
  mlprodict/onnxrt/ops_cpu/op_stft.py
  mlprodict/onnxrt/ops_cpu/op_window.py
  mlprodict/onnxrt/ops_shape/__init__.py
  mlprodict/onnxrt/ops_shape/_element_unary.py
Labels: Opset 17

#464 Implements OnnxLoop
  _unittests/ut_npy/test_xop.py
  mlprodict/npy/xop.py
  mlprodict/onnxrt/onnx_inference_node.py
  mlprodict/onnxrt/ops_cpu/op_loop.py
  mlprodict/onnxrt/ops_shape/shape_result.py
  mlprodict/plotting/text_plot.py
Labels: API
