Repository sdpython/mlprodict, pull requests merged in 2022-07, with the labels that each got.

#444 Fixes a bug in to_onnx when as_function=True
  _doc/notebooks/onnx_sklearn_functions.ipynb
  _unittests/ut__skl2onnx/test_sklearn_pipeline.py
  _unittests/ut_documentation/test_run_notebooks_onnx_sklearn.py
  _unittests/ut_plotting/test_plotting_onnx.py
  _unittests/ut_tools/test_export_onnx_functions.py
  mlprodict/onnx_conv/convert.py
  mlprodict/onnx_tools/onnx2py_helper.py
  mlprodict/onnx_tools/onnx_export.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/onnx_inference_exports.py
  mlprodict/plotting/text_plot.py
Labels: bug

#446 Creates an exporter to python
  _unittests/ut_npy/test_onnx_if.py
  _unittests/ut_tools/test_export_onnx.py
  mlprodict/onnx_tools/_onnx_export_templates_cpp.tmpl
  mlprodict/onnx_tools/_onnx_export_templates_python.tmpl
  mlprodict/onnx_tools/exports/numpy_helper.py
  mlprodict/onnx_tools/onnx_export.py
  mlprodict/onnx_tools/onnx_export_templates.py
Labels: agility

#447 Adds an example to check export issues
  .gitignore
  _doc/examples/plot_export_onnx_tests.py
  _doc/sphinxdoc/source/api/tools.rst
  mlprodict/onnx_tools/exports/numpy_helper.py
  mlprodict/onnx_tools/onnx_export.py
  mlprodict/testing/onnx_backend.py
Labels: documentation

#448 Fixes template to export an onnx graph to python
  mlprodict/onnx_tools/_onnx_export_templates_python.tmpl
Labels: bug

#450 Implements node Expression to compress graph
  _doc/sphinxdoc/source/api/tools.rst
  _unittests/ut_tools/test_compress_onnx.py
  mlprodict/onnx_tools/compress.py
  mlprodict/onnxrt/ops_cpu/_op_list.py
  mlprodict/onnxrt/ops_cpu/op_expression.py
  mlprodict/plotting/text_plot.py
Labels: agility

#451 Adds a table for all versions and all operators
  _unittests/ut_npy/test_xop_doc.py
  mlprodict/npy/xop_auto.py
Labels: documentation

#452 Extends code coverage
  _unittests/ut_onnxrt/test_backend.py
  _unittests/ut_tools/test_compress_onnx.py
  _unittests/ut_tools/test_export_onnx.py
  _unittests/ut_tools/test_ort.py
  mlprodict/cli/einsum.py
  mlprodict/cli/onnx_code.py
  mlprodict/npy/xop.py
  mlprodict/npy/xop_auto.py
  mlprodict/npy/xop_helper.py
  mlprodict/onnx_conv/convert.py
  mlprodict/onnx_tools/onnx2py_helper.py
  mlprodict/onnx_tools/onnx_export.py
  mlprodict/onnxrt/backend.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/ops_cpu/op_grid_sample.py
  mlprodict/onnxrt/ops_cpu/op_if.py
  mlprodict/onnxrt/ops_cpu/op_linear_classifier.py
  mlprodict/onnxrt/ops_cpu/op_max.py
  mlprodict/onnxrt/ops_cpu/op_min.py
  mlprodict/onnxrt/ops_cpu/op_unsqueeze.py
  mlprodict/plotting/text_plot.py
  mlprodict/sklapi/onnx_tokenizer.py
Labels: coverage

#454 Fixes compilation issues on windows and python 3.10
  mlprodict/onnxrt/ops_cpu/op_common_.hpp
  mlprodict/testing/experimental_c_impl/experimental_c_helper.h
Labels: bug

#455 Fixes division by zero in Normalizer
  mlprodict/onnxrt/ops_cpu/op_normalizer.py
  setup.py
Labels: bug, runtime

#456 Fixes python runtime for TfIdfVectorizer
  _unittests/ut__skl2onnx/test_sklearn_tfidf_vectorizer_converter.py
  _unittests/ut_onnx_conv/test_onnx_conv_tree_ensemble.py
  mlprodict/onnx_conv/convert.py
  mlprodict/onnx_tools/exports/tf2onnx_helper.py
  mlprodict/onnx_tools/onnx_manipulations.py
  mlprodict/onnxrt/ops_cpu/op_tfidfvectorizer.py
  mlprodict/onnxrt/ops_cpu/op_tfidfvectorizer_.cpp
  mlprodict/testing/test_utils/utils_backend_common.py
Labels: bug, runtime

#341 Switches CI to python 3.10
  .circleci/config.yml
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  requirements.txt
Labels: ci
