Repository sdpython/mlprodict, pull requests merged in 2022-05, with the labels that each got.

#429 Adds more functions to manipulate graphs
  _doc/sphinxdoc/source/api/tools.rst
  _unittests/ut_module/test_code_style.py
  _unittests/ut_onnx_conv/test_onnx_conv_tree_ensemble.py
  _unittests/ut_onnxrt/test_bugs_onnxruntime.py
  _unittests/ut_onnxrt/test_onnxrt_model_shaker.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_ml_tree.py
  _unittests/ut_onnxrt/test_rt_valid_model_gradient_boosting.py
  _unittests/ut_plotting/test_text_plotting.py
  _unittests/ut_tools/data/fft/dft.onnx
  _unittests/ut_tools/data/fft/dft_last_axis.onnx
  _unittests/ut_tools/data/fft/idft.onnx
  _unittests/ut_tools/data/fft/istft.onnx
  _unittests/ut_tools/data/fft/stft.onnx
  _unittests/ut_tools/data/fft/switch_axes.onnx
  _unittests/ut_tools/data/switch_axes.inlined.onnx
  _unittests/ut_tools/test_export_onnx.py
  _unittests/ut_tools/test_onnx_manipulations.py
  azure-pipelines.yml
  mlprodict/onnx_tools/_onnx_export_templates_cpp.tmpl
  mlprodict/onnx_tools/model_checker.py
  mlprodict/onnx_tools/onnx_export.py
  mlprodict/onnx_tools/onnx_export_templates.py
  mlprodict/onnx_tools/onnx_manipulations.py
  mlprodict/onnx_tools/optim/_onnx_optimisation_common.py
  mlprodict/onnx_tools/optim/onnx_optimisation.py
  mlprodict/onnx_tools/optim/onnx_optimisation_identity.py
  mlprodict/onnx_tools/optim/onnx_optimisation_redundant.py
  mlprodict/onnx_tools/optim/onnx_optimisation_unused.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/onnx_inference_node.py
  mlprodict/onnxrt/ops_cpu/_op.py
  mlprodict/onnxrt/ops_cpu/op_constant.py
  mlprodict/onnxrt/ops_cpu/op_if.py
  mlprodict/plotting/plotting.py
  mlprodict/plotting/text_plot.py
  requirements-osx.txt
  requirements-win.txt
  requirements.txt
Labels: agility

#428 Investigates SVC discrepancies
  _unittests/ut__skl2onnx/test_sklearn_svm_converters.py
  _unittests/ut_onnxrt/test_rt_valid_model_svm.py
  mlprodict/onnx_conv/sklconv/svm_converters.py
  mlprodict/onnxrt/ops_cpu/op_svm_classifier_.cpp
  mlprodict/onnxrt/ops_cpu/op_svm_common_.hpp
  mlprodict/testing/test_utils/utils_backend_common.py
Labels: bug

#430 Adds function to rename inputs or outputs
  _doc/sphinxdoc/source/api/tools.rst
  _unittests/ut_onnx_conv/test_onnx_conv_knn.py
  _unittests/ut_tools/data/fft2/blackman_window.onnx
  _unittests/ut_tools/data/fft2/dft.onnx
  _unittests/ut_tools/data/fft2/dft_inv.onnx
  _unittests/ut_tools/data/fft2/dft_last_axis.onnx
  _unittests/ut_tools/data/fft2/hamming_window.onnx
  _unittests/ut_tools/data/fft2/hann_window.onnx
  _unittests/ut_tools/data/fft2/istft.onnx
  _unittests/ut_tools/data/fft2/stft.onnx
  _unittests/ut_tools/data/fft2/switch_axes.onnx
  _unittests/ut_tools/test_onnx_manipulations.py
  mlprodict/onnx_conv/sklconv/function_transformer_converters.py
  mlprodict/onnx_tools/exports/skl2onnx_helper.py
  mlprodict/onnx_tools/onnx2py_helper.py
  mlprodict/onnx_tools/onnx_export.py
  mlprodict/onnx_tools/onnx_manipulations.py
  mlprodict/onnx_tools/optim/graph_schema_helper.py
  mlprodict/onnxrt/onnx_inference_node.py
  mlprodict/onnxrt/ops_onnxruntime/_op.py
  mlprodict/plotting/text_plot.py
Labels: enhancement, agility

#431 Adds functions to change the shape of inputs and outputs
  _unittests/ut_tools/data/dft_last_axis.error.ort.exec.onnx
  _unittests/ut_tools/data/dft_last_axis.onnxruntime1.output.onnx
  _unittests/ut_tools/data/fft2/dft.onnx
  _unittests/ut_tools/data/fft2/dft_inv.onnx
  _unittests/ut_tools/data/fft2/dft_last_axis.onnx
  _unittests/ut_tools/data/fft2/istft.onnx
  _unittests/ut_tools/data/fft2/stft.onnx
  _unittests/ut_tools/test_bug_ort.py
  _unittests/ut_tools/test_onnx_manipulations.py
  mlprodict/onnx_tools/onnx_manipulations.py
  mlprodict/onnxrt/onnx_inference.py
  mlprodict/onnxrt/onnx_inference_node.py
  mlprodict/onnxrt/ops_whole/session.py
Labels: enhancement

#432 None and [] should be different function get_tensor_shape
  _unittests/ut_tools/data/fft2/dft_last_axis.onnx
  _unittests/ut_tools/data/fft2/istft.onnx
  _unittests/ut_tools/test_bug_ort.py
  _unittests/ut_tools/test_onnx2py_helper.py
  _unittests/ut_tools/test_onnx_manipulations.py
  mlprodict/onnx_tools/onnx2py_helper.py
  mlprodict/onnx_tools/onnx_manipulations.py
  mlprodict/plotting/text_plot.py
Labels: bug

#398 Improves OnnxIf to handle contextual results
  _unittests/ut_npy/test_custom_embedded_any_models.py
  _unittests/ut_npy/test_xop.py
  mlprodict/npy/xop.py
  mlprodict/npy/xop_variable.py
  mlprodict/onnx_tools/model_checker.py
  mlprodict/onnxrt/ops_cpu/op_tfidfvectorizer.py
Labels: bug, API
