Repository sdpython/mlprodict, pull requests merged in 2022-02, with the labels that each got.

#343 Shows links in onnx_simple_text_plot
  _doc/examples/plot_op_reducesumsquare.py
  _unittests/ut_plotting/test_text_plotting.py
  mlprodict/plotting/text_plot.py
Labels: agility

#344 Adds a method to_onnx to easily retrieve the onnx graph from numpy onnx function
  _doc/notebooks/numpy_api_onnx_ftr.ipynb
  _doc/notebooks/onnx_fft.ipynb
  _unittests/ut_npy/test_onnx_variable.py
  _unittests/ut_npy/test_onnx_variable_ort.py
  _unittests/ut_npy/test_onnx_variable_tuple.py
  _unittests/ut_npy/test_wrappers.py
  mlprodict/npy/onnx_numpy_compiler.py
  mlprodict/npy/onnx_numpy_wrapper.py
  mlprodict/npy/onnx_version.py
Labels: agility

#347 numpy API for onnx: wrapped function can call other wrapped functions
  _unittests/ut_npy/test_complex_scenario.py
  mlprodict/npy/onnx_numpy_wrapper.py
Labels: agility

#346 Adds runtime for operator CastLike
  _doc/sphinxdoc/source/api/tools.rst
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  mlprodict/onnxrt/ops_cpu/_op_list.py
  mlprodict/onnxrt/ops_cpu/op_cast.py
Labels: operator

#350 First version of runtime OnnxShapeInference
  _doc/notebooks/loss_functions.ipynb
  _doc/sphinxdoc/source/api/onnxrt.rst
  _unittests/ut_module/test_code_style.py
  _unittests/ut_npy/test_complex_scenario.py
  _unittests/ut_npy/test_onnx_variable.py
  _unittests/ut_onnxrt/test_shape_inference.py
  _unittests/ut_sklapi/test_onnx_tokenizer.py
  mlprodict/npy/__init__.py
  mlprodict/npy/onnx_numpy_wrapper.py
  mlprodict/npy/onnx_variable.py
  mlprodict/onnxrt/__init__.py
  mlprodict/onnxrt/onnx_shape_inference.py
  mlprodict/onnxrt/ops_shape/__init__.py
  mlprodict/onnxrt/ops_shape/_element_wise.py
  mlprodict/onnxrt/ops_shape/shape_container.py
  mlprodict/onnxrt/ops_shape/shape_result.py
  mlprodict/sklapi/onnx_tokenizer.py
Labels: enhancement

#351 Adds name in ShapeResult, fixes zoo links
  README.rst
  _unittests/ut_onnxrt/test_shape_inference.py
  azure-pipelines.yml
  mlprodict/onnx_tools/exports/numpy_helper.py
  mlprodict/onnxrt/onnx_shape_inference.py
  mlprodict/onnxrt/ops_shape/__init__.py
  mlprodict/onnxrt/ops_shape/_element_wise.py
  mlprodict/onnxrt/ops_shape/shape_container.py
  mlprodict/onnxrt/ops_shape/shape_result.py
  mlprodict/tools/zoo.py
Labels: bug

#355 Fixes for onnx==1.11
  .gitignore
  _unittests/ut_onnx_conv/test_onnxrt_runtime_lightgbm.py
  _unittests/ut_onnx_conv/test_onnxrt_runtime_lightgbm_bug.py
  _unittests/ut_onnxrt/test_rt_valid_model_isolationforest.py
  mlprodict/onnx_conv/convert.py
  mlprodict/onnx_conv/operator_converters/conv_xgboost.py
  mlprodict/onnxrt/validate/validate.py
  mlprodict/sklapi/onnx_tokenizer.py
  mlprodict/tools/asv_options_helper.py
  requirements.txt
Labels: bug, ci

#353 Experimentations with a new API to create ONNX graphs
  _doc/sphinxdoc/source/_exts/generate_onnx_ops.py
  _doc/sphinxdoc/source/api/index.rst
  _doc/sphinxdoc/source/api/xop.rst
  _doc/sphinxdoc/source/api/xop_supported.rst
  _doc/sphinxdoc/source/conf.py
  _unittests/ut_cli/test_cli_dynamic_doc.py
  _unittests/ut_cli/test_cli_onnx_code.py
  _unittests/ut_npy/test_xop.py
  _unittests/ut_npy/test_xop_doc.py
  mlprodict/__main__.py
  mlprodict/cli/onnx_code.py
  mlprodict/npy/_cache/__init__.py
  mlprodict/npy/onnx_numpy_compiler.py
  mlprodict/npy/onnx_numpy_wrapper.py
  mlprodict/npy/onnx_sklearn_wrapper.py
  mlprodict/npy/onnx_variable.py
  mlprodict/npy/xop.py
  mlprodict/npy/xop_auto.py
  mlprodict/npy/xop_auto_import_.py
  mlprodict/npy/xop_ops.py
  mlprodict/npy/xop_opset.py
  mlprodict/npy/xop_variable.py
  mlprodict/onnx_tools/onnx2py_helper.py
  mlprodict/onnx_tools/optim/onnx_helper.py
Labels: enhancement

#356 Supports multiple affectations (xop)
  _doc/sphinxdoc/source/_exts/generate_onnx_ops.py
  _unittests/ut_npy/test_xop.py
  mlprodict/npy/xop.py
  mlprodict/npy/xop_ops.py
Labels: agility, API

#357 Modifies OnnxShapeInference to deal with untyped outputs
  _unittests/ut_onnxrt/test_shape_inference_xop.py
  mlprodict/npy/xop.py
  mlprodict/onnxrt/onnx_shape_inference.py
  mlprodict/onnxrt/ops_shape/shape_container.py
  mlprodict/onnxrt/ops_shape/shape_result.py
Labels: agility, API

#358 Extends supported operator by OnnxShapeInference
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_.py
  mlprodict/onnxrt/ops_shape/__init__.py
  mlprodict/onnxrt/ops_shape/_element_unary.py
  mlprodict/onnxrt/ops_shape/_element_wise.py
Labels: agility

#359 Supports domains in Xop API
  _doc/sphinxdoc/source/conf.py
  _unittests/ut_npy/test_xop.py
  _unittests/ut_onnxrt/test_shape_inference_xop.py
  mlprodict/npy/xop.py
  mlprodict/npy/xop_auto.py
  mlprodict/npy/xop_auto_import_.py
  mlprodict/npy/xop_opset.py
  mlprodict/npy/xop_variable.py
Labels: agility, API

#360 Xop API, adds class OnnxSubOnnx to insert ONNX graph
  _doc/sphinxdoc/source/_exts/generate_onnx_ops.py
  _doc/sphinxdoc/source/api/ast.rst
  _doc/sphinxdoc/source/api/index.rst
  _doc/sphinxdoc/source/api/xop.rst
  _doc/sphinxdoc/source/tutorial/index.rst
  _doc/sphinxdoc/source/tutorial/numpy_api_onnx.rst
  _doc/sphinxdoc/source/tutorial/onnx_numpy.rst
  _doc/sphinxdoc/source/tutorial/onnx_runtime.rst
  _doc/sphinxdoc/source/tutorial/skl.rst
  _doc/sphinxdoc/source/tutorial/xop_api.rst
  _unittests/ut_npy/test_xop_convert.py
  mlprodict/npy/xop.py
  mlprodict/npy/xop_auto.py
  mlprodict/npy/xop_auto_import_.py
  mlprodict/npy/xop_convert.py
  mlprodict/npy/xop_opset.py
  mlprodict/npy/xop_variable.py
  mlprodict/onnx_tools/onnx_grammar/onnx_translation.py
  mlprodict/onnxrt/doc/doc_helper.py
Labels: API

#363 Refactoring, moving files testing.experimental_c
  _doc/examples/plot_logistic_regression.py
  _doc/examples/plot_op_add.py
  _doc/examples/plot_op_einsum.py
  _doc/examples/plot_op_onnx_topk.py
  _doc/examples/plot_op_reducemax.py
  _doc/examples/plot_op_reducemean.py
  _doc/examples/plot_op_reducesum.py
  _doc/examples/plot_op_reducesumsquare.py
  _doc/examples/plot_op_transpose.py
  _doc/examples/plot_op_where.py
  _doc/examples/plot_opml_linear_regression.py
  _doc/examples/plot_opml_random_forest_cls_multi.py
  _doc/examples/plot_opml_random_forest_reg.py
  _doc/examples/plot_parallelism.py
  _doc/examples/plot_time_tree_ensemble.py
  _doc/sphinxdoc/source/api/testing.rst
  _unittests/ut_testing/test_custom_add.py
  _unittests/ut_testing/test_experimental.py
  mlprodict/testing/experimental_c_impl/__init__.py
  mlprodict/testing/experimental_c_impl/experimental_c.cpp
  mlprodict/testing/experimental_c_impl/experimental_c.h
  mlprodict/testing/experimental_c_impl/experimental_c_add.h
  mlprodict/testing/experimental_c_impl/experimental_c_add.hpp
  mlprodict/testing/experimental_c_impl/experimental_c_einsum.h
  mlprodict/testing/experimental_c_impl/experimental_c_einsum.hpp
  mlprodict/testing/experimental_c_impl/experimental_c_helper.h
  mlprodict/testing/experimental_c_impl/experimental_c_helper.hpp
  mlprodict/testing/experimental_c_impl/experimental_c_reduce.h
  mlprodict/testing/experimental_c_impl/experimental_c_reduce.hpp
  setup.py
Labels: refactoring

#362 Adds command line plot_onnx
  _unittests/ut_cli/test_cli_onnx_code.py
  _unittests/ut_module/test_setup.py
  mlprodict/__main__.py
  mlprodict/cli/onnx_code.py
Labels: agility

#364 Runs onnx backend test with python runtime
  _doc/sphinxdoc/source/api/onnxrt.rst
  _doc/sphinxdoc/source/api/tools.rst
  _doc/sphinxdoc/source/tutorial/index.rst
  _unittests/ut_cli/test_cli_onnx_code.py
  _unittests/ut_testing/test_onnx_backend.py
  mlprodict/testing/experimental_c_impl/__init__.py
  mlprodict/testing/onnx_backend.py
  setup.py
Labels: runtime

#365 Adds command line benchmark_doc
  _doc/sphinxdoc/source/_exts/generate_automated_pages.py
  _unittests/ut_cli/test_cli_validate_bench_doc.py
  bin/run_bench_documentation.sh
  mlprodict/__main__.py
  mlprodict/cli/validate.py
Labels: ci, agility

#366 Adds python runtime for CategoryMapper
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_ml.py
  _unittests/ut_onnxrt/test_onnxrt_python_runtime_ml_text.py
  mlprodict/onnxrt/ops_cpu/_op_list.py
  mlprodict/onnxrt/ops_cpu/op_category_mapper.py
Labels: runtime

#367 Refactors results name in Xop API
  _doc/sphinxdoc/source/_exts/generate_onnx_ops.py
  _doc/sphinxdoc/source/api/xop_supported.rst
  _doc/sphinxdoc/source/tutorial/xop_api.rst
  _unittests/ut_npy/test_xop.py
  _unittests/ut_npy/test_xop_convert.py
  _unittests/ut_npy/test_xop_infer.py
  _unittests/ut_npy/test_xop_onnxruntime.py
  mlprodict/npy/xop.py
  mlprodict/npy/xop_convert.py
  mlprodict/npy/xop_variable.py
Labels: bug, API

#368 Updates requirements, skl2onnx>=1.11
  requirements-osx.txt
  requirements.txt
Labels: ci

#369 Supports recursive display in onnx_simple_text_plot
  _doc/sphinxdoc/source/tutorial/xop_api.rst
  _unittests/ut_plotting/test_text_plotting.py
  mlprodict/plotting/text_plot.py
Labels: agility
